### ISSUE TITLE
how to enable web profiler

### ISSUE THREAD

**Issue by gitdiz** [philiplb/CRUDlexSilex2Sample#1]
Hi,
I began to play around with crudlex (crudlex-sample)and  would like to use the web-profiler for debugging (according to https://github.com/silexphp/Silex-WebProfiler). This ends in a version conflict: 

`silex/web-profiler 2.0.x-dev requires silex/silex 2.0.*@dev -> satisfiable by silex/silex[2.0.x-dev] but these conflict with your requirements or minimum-stability`

Maybe you know  a way how to resolve this? Thanks for offering CRUDlex!! dirk

**Comment by philiplb** [comment]
Hi,
as there is no stable version of Silex 2.0 released yet, I haven't tested it yet with CRUDlex and offer no support for it yet. This will happen as soon as Silex 2.0 is released.
Meanwhile, you could just use the Web Profiler v1.0.8:

``` bash
composer require silex/web-profiler v1.0.8
```

**Comment by gitdiz** [comment]
Ah, thank you!
